def drawingPics():
    print("          *          ")
    print("         * *         ")
    print("         * *         ")
    print("        *   *        ")
    print("        *   *        ")
    print("       *     *       ")
    print("      *       *      ")
    print("     *         *     ")
    print("    *           *    ")
    print("     *         *     ")
    print("   *             *   ")
    print("  *               *  ")
    print(" *                 * ")
    print("*********************")
    print("        *****        ")
    print("        *****        ")
    print("        *****        ")
    print("        *****        ")
    print("        *****        ")

drawingPics()
